ShopGUI
UInt32 [] ShopGUI.itemCost
Array containing the cost of each item.
Texture ShopGUI.checkTick
Image texture of the check for labeling owned items.
Referenced by _Ready, OnBuyPressed.
int ShopGUI.selected
The currently selected item.
Referenced by OnBuyPressed.
string [] ShopGUI.keys
Keys for labeling items.
delegate void ShopGUI.ProfileChanged()
Emitted if the player profile changed. (If an item was bought)
override void ShopGUI._Ready()
References PlayerSession.ActiveSession, checkTick, Palette.Instance, OnBuyPressed, OnCancelPressed, OnItemButtonPressed, SaveFileInfo.OWNED_ITEMS_BUFFER_LENGTH, Profile.OwnedItems, PlayerSession.Profile, Palette.TextureFromColor, Main.WINDOW_SIZE.
void ShopGUI.OnItemButtonPressed()
Referenced by _Ready.
void ShopGUI.OnCancelPressed()
Referenced by _Ready.
void ShopGUI.OnBuyPressed()
References PlayerSession.ActiveSession, checkTick, Profile.OwnedItems, Profile.Points, PlayerSession.Profile, PlayerSession.Save, selected.
Referenced by _Ready.