Avatar
bool Avatar.Male
The avatar's Gender. True if male, false if female.
Referenced by Player._Ready, EditProfileGUI._Ready, Avatar, Clone, EditProfileGUI.OnGenderItemSelected, EditProfileGUI.OnSavePressed, Profile.ToBytes, ToTexture, EditProfileGUI.UnsavedChanges, EditProfileGUI.UpdateAvatar.
int Avatar.SkinColor
Id of the avatar's skin color.
Referenced by Avatar, Clone, GetColor, SetColor, Profile.ToBytes.
int Avatar.TopColor
Id of the avatar's bottom color.
Referenced by Player._Ready, Avatar, Clone, GetColor, SetColor, Profile.ToBytes.
int Avatar.BottomColor
Id of the avatar's top color.
Referenced by Player._Ready, Avatar, Clone, GetColor, SetColor, Profile.ToBytes.
readonly Texture Avatar.EMPTY_SAVE_AVATAR
Default avatar for non-created profiles.
Referenced by ProfileSelectEntry.UpdateUI.
Avatar.Avatar(bool male, int skinColor, int topColor, int bottomColor)
Creates a new avatar from the supplied data.
male The avatar's Gender. True if male, false if female. skinColor Id of the avatar's skin color. topColor Id of the avatar's bottom color. bottomColor Default avatar for non-created profiles.
References BottomColor, Male, SkinColor, TopColor.
Referenced by Clone.
int Avatar.GetColor(string key)
Gets one of the avatar's colors from a given string.
key Can be Skin, Top or Bottom. The color corresponding to the string.
References BottomColor, SkinColor, TopColor.
Referenced by EditProfileGUI._Ready, ToTexture.
void Avatar.SetColor(string key, int color)
Sets one of the avatar's colors from a given string.
key Can be Skin, Top or Bottom.
References BottomColor, SkinColor, TopColor.
Referenced by EditProfileGUI.UpdateAvatar.
Texture Avatar.ToTexture()
Performs a palette swap on the default avatar, swapping the default colors for the colors specified in each property. Converts the avatar into an image texture.
The avatar as an image texture.
References Palette.DEFAULT_COLORS_FEMALE, Palette.DEFAULT_COLORS_MALE, Palette.DEFAULT_THRESHOLD, GetColor, Palette.Instance, PaletteSwapShader.Instance, Male, Palette.PaletteColors, PaletteSwapShader.PaletteSwap.
Referenced by EditProfileGUI.UpdateAvatar, ProfileGUI.UpdateUI, ProfileSelectEntry.UpdateUI.
Avatar Avatar.Clone()
Clones the avatar.
A copy of the avatar.
References Avatar, BottomColor, Male, SkinColor, TopColor.