ProfileSelectEntry
int ProfileSelectEntry.ProfileID
The profile's id.
override void ProfileSelectEntry._Ready()
References OnCreateDialogCreationFailed, OnDeleteDialogConfirmed, OnDeletePressed, OnPressed, UpdateUI.
void ProfileSelectEntry.UpdateUI()
Updates the data currently displayed on the button.
References Profile.Avatar, Profile.CompletedLevels, Avatar.EMPTY_SAVE_AVATAR, Profile.Exists, Profile.Get, Profile.Name, Profile.NumberOfOwnedItems, Avatar.ToTexture.
Referenced by _Ready, OnDeleteDialogConfirmed.
void ProfileSelectEntry.OnDeletePressed()
Referenced by _Ready.
void ProfileSelectEntry.OnDeleteDialogConfirmed()
References Profile.Delete, UpdateUI.
Referenced by _Ready.
void ProfileSelectEntry.OnCreateDialogCreationFailed()
Referenced by _Ready.
void ProfileSelectEntry.OnPressed()
References PlayerSession.ActiveSession, Profile.Exists, PlayerSession.Load.
Referenced by _Ready.