GameHUD
delegate void GameHUD.PausePressed()
Signal emitted when the pause button is pressed.
delegate void GameHUD.PauseMouseEntered()
Signal emitted when the mouse enters the pause button area.
delegate void GameHUD.PauseMouseExited()
Signal emitted when the mouse exits the pause button area.
override void GameHUD._Ready()
References OnPauseMouseEntered, OnPauseMouseExited, OnPausePressed.
void GameHUD.SetPoints(int points)
Sets the number of points to display in the points counter.
points The new number of points to display.
Referenced by Level._Process.
void GameHUD.SetProgress(double percent)
Sets the progress to display in the level progress bar.
percent The player's new progress.
Referenced by Level._Process.
void GameHUD.SetAttempts(int number)
Sets the number of attempts to display on the attempts counter.
number The player's new number of attempts.
Referenced by Level.Restart.
void GameHUD.SetActions(PlayerMainAction main, PlayerSecondaryAction secondary)
Sets the player actions to display on the hud.
main The main action the player currently has. secondary The secondary action the player currently has.
References MainAction.GetTypeAsStringEsp, SecondaryAction.GetTypeAsStringEsp.
Referenced by Level._Process.
void GameHUD.OnPausePressed()
Referenced by _Ready.
void GameHUD.OnPauseMouseEntered()
Referenced by _Ready.
void GameHUD.OnPauseMouseExited()
Referenced by _Ready.