PlayerStateFactory
PersistentState PlayerStateFactory.New(PlayerPersistentState state)
Creates a new persistent state from the given enum value.
state The value of the new state. A new instance of a player persistent state.
Referenced by Player.ChangeMainAction, Player.ChangePersistentState, Player.ChangeSecondaryAction.
MainAction PlayerStateFactory.New(PlayerMainAction state)
Creates a new player primary action from the given enum value.
state The value of the new primary action. A new instance of a player primary action.
SecondaryAction PlayerStateFactory.New(PlayerSecondaryAction state)
Creates a new secondary action from the given enum value.
state The value of the new secondary action. A new instance of a player secondary action.