PauseMenu
delegate void PauseMenu.RestartPressed()
Signal that will be emitted when the restart button is pressed.
override void PauseMenu._Ready()
References OnCancelPressed, OnContinuePressed, OnQuitPressed, OnRestartPressed, Main.WINDOW_SIZE.
void PauseMenu.ShowMenu()
Pauses the game and shows this menu.
Referenced by Level.Pause.
void PauseMenu.OnCancelPressed()
References OnContinuePressed.
Referenced by _Ready.
void PauseMenu.OnContinuePressed()
Referenced by _Ready, OnCancelPressed.
void PauseMenu.OnRestartPressed()
Referenced by _Ready.
void PauseMenu.OnQuitPressed()
Referenced by _Ready.