PlayerState
Player PlayerState.Player
The player that owns the current state.
void PlayerState.Setup()
Setups the state and initializes it.
References _Init.
Referenced by Player.ChangeMainAction, Player.ChangePersistentState, Player.ChangeSecondaryAction.
abstract void PlayerState._StatePhysicsProcess(float delta)
The physics process that will be called each frame for the state.
delta Time since the last frame.
abstract void PlayerState._Init()
Setups the state and initializes it.
Referenced by Setup.