Level
PackedScene Level.Player
The player scene from which to load instances.
float Level.pointsMultiplier
A value that will be multiplied with the points earned.
Player Level.player
The currently active player in the level.
Camera2D Level.camera
The game's camera.
AnimatedSprite Level.background
The level's background.
PauseMenu Level.pauseMenu
The level's pause menu.
LevelComplete Level.levelCompleteMenu
Menu that will be shown when level is completed.
GameHUD Level.hud
Game hud.
Position2D Level.startPosition
The player's spawn position.
Area2D Level.endPosition
The player's position where the level ends.
int Level.attemptCount
The number of times the player has attempted the level.
double Level.progress
The current progress the player has on the level.
int Level.LevelNumber
The level's number.
Referenced by SaveData.
List<Vector2> Level.positions
override void Level._Ready()
References OnEndPositionBodyEntered, OnHudPauseMouseEntered, OnHudPauseMouseExited, OnHudPausePressed, OnPauseMenuRestartPressed, Restart.
override void Level._Process(float delta)
References GetPoints, Player.MainActionType, MoveViewPort, Pause, GameHUD.SetActions, GameHUD.SetPoints, GameHUD.SetProgress, UpdateProgress.
override void Level._Draw()
void Level.Restart()
Restarts the level, resets the player's position and the hud.
References OnPlayerDead, SaveData, GameHUD.SetAttempts.
Referenced by _Ready, OnPauseMenuRestartPressed, OnPlayerDead.
void Level.UpdateProgress()
Calculates the progress that the player currently has on the level.
Referenced by _Process.
int Level.GetPoints()
Gets the number of points that the player has earned on the current run.
References PlayerSession.ActiveSession, Profile.LevelProgress, PlayerSession.Profile.
Referenced by _Process, SaveData.
void Level.MoveViewPort()
Moves the camera and the background to follow the player.
Referenced by _Process.
void Level.Pause()
Pauses the game.
References PauseMenu.ShowMenu.
Referenced by _Process, OnHudPausePressed.
void Level.SaveData()
Saves the player's progress.
References PlayerSession.ActiveSession, GetPoints, LevelNumber, Profile.LevelProgress, Profile.Points, PlayerSession.Profile, PlayerSession.Save.
Referenced by Restart.
void Level.OnPlayerDead()
References Restart.
Referenced by Restart.
void Level.OnHudPausePressed()
References Pause.
Referenced by _Ready.
void Level.OnHudPauseMouseEntered()
References Player.Blocked.
Referenced by _Ready.
void Level.OnHudPauseMouseExited()
References Player.Blocked.
Referenced by _Ready.
void Level.OnPauseMenuRestartPressed()
References Restart.
Referenced by _Ready.
void Level.OnEndPositionBodyEntered(Node body)
References LevelComplete.ShowMenu.
Referenced by _Ready.