ProfileGUI
delegate void ProfileGUI.ShopPressed()
Emitted when the shop button is pressed.
delegate void ProfileGUI.EditPressed()
Emitted when the edit profile button is pressed.
override void ProfileGUI._Ready()
References OnEditPressed, OnLogOutPressed, OnShopPressed, UpdateUI.
void ProfileGUI.UpdateUI()
Updates the information currently displayed on the GUI.
References PlayerSession.ActiveSession, Profile.Avatar, Profile.CompletedLevels, Profile.Name, PlayerSession.Profile, Avatar.ToTexture.
Referenced by _Ready.
void ProfileGUI.OnShopPressed()
Referenced by _Ready.
void ProfileGUI.OnEditPressed()
Referenced by _Ready.
void ProfileGUI.OnLogOutPressed()
References PlayerSession.ActiveSession, PlayerSession.LogOut.
Referenced by _Ready.