LevelComplete
delegate void LevelComplete.RestartPressed()
Signal that will be emitted when the restart button is pressed.
override void LevelComplete._Ready()
References OnQuitPressed, OnRestartPressed, Main.WINDOW_SIZE.
void LevelComplete.ShowMenu()
Pauses the game and shows this menu.
Referenced by Level.OnEndPositionBodyEntered.
void LevelComplete.OnRestartPressed()
Referenced by _Ready.
void LevelComplete.OnQuitPressed()
Referenced by _Ready.