MainAction
bool MainAction.OnActionPad
True if the player is currently on a jump pad.
Referenced by Glide._ActionOnAir, _ActionOnAir, Teleport._ActionOnAir, Glide.OnMainActionObjectCollisionCheckAreaEntered, OnMainActionObjectCollisionCheckAreaEntered, Teleport.OnMainActionObjectCollisionCheckAreaEntered, OnMainActionObjectCollisionCheckAreaExited.
bool MainAction.PerformingAction
True if the player is currently performing a main action.
Referenced by _ActionOnAir, Teleport._ActionOnAir, _ActionOnGround, Teleport._ActionOnGround, Jetpack._ActionReleased, Teleport._ActionReleased, OnAirState._Init, _StatePhysicsProcess, OnMainActionObjectCollisionCheckAreaEntered, OnMainActionTimerTimeout.
bool MainAction.Blocked
Checks if the current action is blocked/disabled. If true, the action will not be performed on input events.
Referenced by FastFallAndRoll._ActionOnGround, SecondaryAction.OnSecondaryActionTimerTimeout.
bool MainAction.CanUseActionPad
True if the player can use jump pads.
Referenced by Glide._ActionOnAir, Teleport._ActionOnAir, Glide._ActionOnGround.
delegate void MainAction.Action()
Emitted if the player performs a main action.
override void MainAction._Init()
Setups the state and initializes it.
References Player.jumpObjectCollisionCheck, Player.mainActionTimer, Player.MaxJumpTime, OnMainActionObjectCollisionCheckAreaEntered, OnMainActionObjectCollisionCheckAreaExited, OnMainActionTimerTimeout.
override void MainAction._StatePhysicsProcess(float delta)
The physics process that will be called each frame for the state.
delta Time since the last frame.
References _ActionOnAir, _ActionOnGround, _ActionProcess, _ActionReleased, PerformingAction, Player.PersistentState.
Referenced by Player._PhysicsProcess.
virtual void MainAction._ActionOnGround()
References Player.linearVelocity, Player.mainActionTimer, PerformingAction.
Referenced by _StatePhysicsProcess.
virtual void MainAction._ActionOnAir()
References Player.linearVelocity, Player.mainActionTimer, OnActionPad, PerformingAction.
Referenced by _StatePhysicsProcess.
virtual void MainAction._ActionReleased()
Referenced by _StatePhysicsProcess.
abstract void MainAction._ActionProcess(float delta)
The process that will be executed each frame while the action is being performed.
delta Time since last frame.
Referenced by _StatePhysicsProcess.
virtual void MainAction.OnMainActionTimerTimeout()
References PerformingAction.
Referenced by _Init.
virtual void MainAction.OnMainActionObjectCollisionCheckAreaEntered(Area2D area)
References Player.linearVelocity, Player.mainActionTimer, OnActionPad, PerformingAction.
Referenced by _Init.
virtual void MainAction.OnMainActionObjectCollisionCheckAreaExited(Area2D area)
References OnActionPad.
Referenced by _Init.
static string MainAction.GetTypeAsString(PlayerMainAction action)
Gets the given action's type as a string. This is because the player animations corresponding to each action has these names.
action The enum value of the action. A string depending on the action type.
Referenced by MainActionPickup._Ready.
static string MainAction.GetTypeAsStringEsp(PlayerMainAction action)
Gets the given action's type as a string in spanish. This is for displaying on the GUI.
action The enum value of the action A string in spanish depending on the action type.
Referenced by GameHUD.SetActions.