Profile
int Profile.ID
The profile id. Can be any number between 0 and 5.
Referenced by Get, Profile.
string Profile.Name
The profile name.
Referenced by EditProfileGUI._Ready, NameIsAvailable, EditProfileGUI.OnSavePressed, Profile, ToBytes, EditProfileGUI.UnsavedChanges, ProfileGUI.UpdateUI, ProfileSelectEntry.UpdateUI.
Avatar Profile.Avatar
The profile's avatar.
Referenced by EditProfileGUI._Ready, EditProfileGUI.OnSavePressed, Profile, EditProfileGUI.UnsavedChanges, ProfileGUI.UpdateUI, ProfileSelectEntry.UpdateUI.
UInt32 Profile.Points
The number of points that the profile currently owns.
Referenced by ShopGUI.OnBuyPressed, Profile, Level.SaveData, MainMenu.UpdateUI.
bool [] Profile.OwnedItems
An array of booleans in which each index corresponds to a store item's id. Each element is true if the item was bought from the store and is currently owned and false otherwise.
Referenced by EditProfileGUI._Process, ShopGUI._Ready, LevelIsUnlocked, ShopGUI.OnBuyPressed, Profile, ToBytes.
int [] Profile.LevelProgress
An array of ints that contains the maximum percent of progress the player has reached in each level. Element 0 is level 1, element 1 is level 2 and element 2 is level 3.
Referenced by Level.GetPoints, Profile, Level.SaveData, ToBytes.
int Profile.CurrentLevel
The level the player is currently in, that being the first level the player hasn't completed or level 3 if all have been completed.
Referenced by LevelPicker._Ready.
List<int> Profile.CompletedLevels
A list of the levels the player has completed.
Referenced by ProfileGUI.UpdateUI, ProfileSelectEntry.UpdateUI.
int Profile.NumberOfOwnedItems
The number of items the player has bought from the store.
Referenced by ProfileSelectEntry.UpdateUI.
readonly string Profile.SAVES_DIRECTORY
Directory where the profiles will be stored.
Referenced by Create, Delete, Exists, Profile, PlayerSession.Save.
readonly int Profile.MAX_NUMBER_OF_SAVES
Maximum number of profiles that can be saved.
Profile.Profile(int id)
Loads an existing profile from a file by the profile's id. If the profile doesn't exist or the save file is corrupted, returns a profile with an id of 6.
id ID of the profile to load.
References Avatar, SaveFileInfo.AVATAR_COLOR_BOTTOM, SaveFileInfo.AVATAR_COLOR_SKIN, SaveFileInfo.AVATAR_COLOR_TOP, SaveFileInfo.AVATAR_GENDER, Delete, Exists, SaveFileInfo.FILE_SIZE, ID, SaveFileInfo.LEVEL1_PROGRESS, SaveFileInfo.LEVEL2_PROGRESS, SaveFileInfo.LEVEL3_PROGRESS, LevelProgress, Name, SaveFileInfo.OWNED_ITEMS, SaveFileInfo.OWNED_ITEMS_BUFFER_LENGTH, OwnedItems, Points, SaveFileInfo.POINTS, SaveFileInfo.PROFILE_NAME, SaveFileInfo.PROFILE_NAME_MAX_SIZE, SAVES_DIRECTORY.
Referenced by Get.
byte[] Profile.ToBytes()
Writes the profile data to an array of bytes for saving in a file.
A byte buffer containing the profile data
References SaveFileInfo.AVATAR_COLOR_BOTTOM, SaveFileInfo.AVATAR_COLOR_SKIN, SaveFileInfo.AVATAR_COLOR_TOP, SaveFileInfo.AVATAR_GENDER, Avatar.BottomColor, SaveFileInfo.FILE_SIZE, SaveFileInfo.LEVEL1_PROGRESS, LevelProgress, Avatar.Male, Name, SaveFileInfo.OWNED_ITEMS, OwnedItems, SaveFileInfo.POINTS, SaveFileInfo.PROFILE_NAME, SaveFileInfo.PROFILE_NAME_MAX_SIZE, Avatar.SkinColor, Avatar.TopColor.
bool Profile.LevelIsUnlocked(int level)
Checks if the level is unlocked, that is if the level's key has been bought from the store.
level The level's number. True if the level is unlocked, else false.
References OwnedItems.
Referenced by LevelPicker.OnValueChanged.
static Profile Profile.Get(int id)
Method that encapsulates the profile's class constructor. Loads the profile with the given id and returns it's data, returning null if the profile doesn't exist. This is used instead of the constructor because constructors can't return null.
id The id of the profile to get. The profile's data or null if the profile doesn't exist.
References ID, Profile.
Referenced by PlayerSession.Load, NameIsAvailable, ProfileSelectEntry.UpdateUI.
static void Profile.Create(int id, string name)
Creates a new profile.
id The id of the new profile. name The profile's name.
References SaveFileInfo.AVATAR_COLOR_BOTTOM, SaveFileInfo.AVATAR_COLOR_SKIN, SaveFileInfo.AVATAR_COLOR_TOP, SaveFileInfo.AVATAR_GENDER, SaveFileInfo.FILE_SIZE, SaveFileInfo.PROFILE_NAME, SAVES_DIRECTORY.
Referenced by CreateProfileDialog.OnCreateProfileDialogConfirmed.
static void Profile.Delete(int id)
Deletes an existing profile save file.
id The profile's id.
References SAVES_DIRECTORY.
Referenced by ProfileSelectEntry.OnDeleteDialogConfirmed, Profile.
static bool Profile.Exists(int id)
Checks if the profile exists.
id The profile's id.
References SAVES_DIRECTORY.
Referenced by NameIsAvailable, ProfileSelectEntry.OnPressed, Profile, ProfileSelectEntry.UpdateUI.
static bool Profile.NameIsAvailable(string name)
Checks if a profile name is available.
name The profile name True if no profile has the name already, else false.
References Exists, Get, Name.
Referenced by CreateProfileDialog.OnCreateProfileDialogConfirmed, EditProfileGUI.OnSavePressed.