Glide
GlideStates
GlideStates Glide.state
The state in which the glide action is currently.
override void Glide._Init()
Setups the state and initializes it.
References Player.DEFAULT_GRAVITY, Player.DEFAULT_JUMPFORCE, Player.DEFAULT_MAX_JUMP_TIME, Player.Gravity, Player.JumpForce, Player.MaxFallSpeed, Player.MaxJumpTime.
override void Glide._StatePhysicsProcess(float delta)
The physics process that will be called each frame for the state.
delta Time since the last frame.
References _ActionOnAir, _ActionOnGround, _ActionProcess, _ActionReleased, Player.DEFAULT_GRAVITY, Player.Gravity, Player.InvertedGravity, Player.PersistentState.
override void Glide._ActionOnGround()
References MainAction.CanUseActionPad, Player.mainActionTimer.
Referenced by _StatePhysicsProcess.
override void Glide._ActionOnAir()
References MainAction.CanUseActionPad, Player.Gravity, Player.mainActionTimer, Player.MaxJumpTime, MainAction.OnActionPad.
Referenced by _StatePhysicsProcess.
override void Glide._ActionReleased()
References Player.DEFAULT_GRAVITY, Player.Gravity, Player.InvertedGravity, Player.mainActionTimer, Player.MaxJumpTime.
Referenced by _StatePhysicsProcess.
override void Glide._ActionProcess(float delta)
The process that will be executed each frame while the action is being performed.
delta Time since last frame.
References Player.JumpForce, Player.linearVelocity.
Referenced by _StatePhysicsProcess.
override void Glide.OnMainActionTimerTimeout()
References Player.DEFAULT_GRAVITY, Player.Gravity, Player.InvertedGravity, Player.mainActionTimer, Player.MaxJumpTime.
override void Glide.OnMainActionObjectCollisionCheckAreaEntered(Area2D area)
References Player.mainActionTimer, Player.MaxJumpTime, MainAction.OnActionPad.