Main
readonly Vector2 Main.WINDOW_SIZE
Size of the game's window.
Referenced by EditProfileGUI._Ready, LevelComplete._Ready, PauseMenu._Ready, ShopGUI._Ready.
Node2D Main.Scene
The scene currently being executed. Can be profile select, main menu, level 1, level 2 or level 3.
Referenced by ChangeScene.
GameAudio Main.gameAudio
SceneFactory Main.sceneFactory
Factory for creating new scene instances.
override void Main._Ready()
References ChangeScene.
void Main.ChangeScene(GameScenes scene)
Changes the currently active game scene and modifies the sounds currently being played accordingly.
scene The new scene.
References SceneFactory.New, OnPlayerDead, OnPlayerPerformedMainAction, OnPlayerPickup, GameAudio.PlayAccept, GameAudio.PlayCancel, Scene, GameAudio.SetMusic.
Referenced by _Ready.
void Main.OnPlayerDead()
References GameAudio.PlayDeath.
Referenced by ChangeScene.
void Main.OnPlayerPickup()
References GameAudio.PlayPickup.
Referenced by ChangeScene.
void Main.OnPlayerPerformedMainAction()
References GameAudio.PlayJump.
Referenced by ChangeScene.