GameAudio
AudioStream GameAudio.MenuMusic
Music to play on menus.
Referenced by _Ready.
AudioStream GameAudio.Level1Music
Level 1 music.
AudioStream GameAudio.Level2Music
Level 2 music.
AudioStream GameAudio.Level3Music
Level 3 music.
AudioStream GameAudio.AcceptSFX
Audio effect to play when clicking an accept button.
Referenced by PlayAccept.
AudioStream GameAudio.CancelSFX
Audio effect to play when clicking an cancel/back button.
Referenced by PlayCancel.
Dictionary<GameScenes, AudioStream> GameAudio.sceneMusic
Dictionary mapping each game scene to a background music track.
AudioStreamPlayer GameAudio.music
The audio player for background music.
AudioStreamPlayer GameAudio.sfx
The audio player for audio effects.
override void GameAudio._Ready()
References MenuMusic, OnMusicFinished, OnSfxFinished.
void GameAudio.SetMusic(GameScenes scene)
Sets a new music track, depending on the scene.
scene The new scene executed by the main scene.
Referenced by Main.ChangeScene.
void GameAudio.PlayAccept()
Plays the accept audio effect.
References AcceptSFX.
Referenced by Main.ChangeScene.
void GameAudio.PlayCancel()
Plays the cancel audio effect.
References CancelSFX.
Referenced by Main.ChangeScene.
void GameAudio.OnMusicFinished()
Referenced by _Ready.
void GameAudio.OnSfxFinished()
Referenced by _Ready.