MainMenu
PackedScene MainMenu.editProfile
The panel for editing the player's profile.
PackedScene MainMenu.shop
The panel that contains the game's shop.
override void MainMenu._Ready()
References OnExitButtonPressed, OnLevelPickerValueChanged, OnPlayButtonPressed, OnProfileGUIEditPressed, OnProfileGUIShopPressed, UpdateUI.
override void MainMenu._Process(float delta)
void MainMenu.UpdateUI()
References PlayerSession.ActiveSession, Profile.Points, PlayerSession.Profile.
Referenced by _Ready, OnProfileChanged.
void MainMenu.OnPlayButtonPressed()
Referenced by _Ready.
void MainMenu.OnProfileGUIShopPressed()
References OnProfileChanged.
Referenced by _Ready.
void MainMenu.OnProfileGUIEditPressed()
References OnProfileChanged.
Referenced by _Ready.
void MainMenu.OnExitButtonPressed()
Referenced by _Ready.
void MainMenu.OnProfileChanged()
References UpdateUI.
Referenced by OnProfileGUIEditPressed, OnProfileGUIShopPressed.
void MainMenu.OnLevelPickerValueChanged()
Referenced by _Ready.