EditProfileGUI
Texture EditProfileGUI.lockSprite
Sprite for labeling items which have not been unlocked yet.
Referenced by _Process.
Avatar EditProfileGUI.editedAvatar
A copy of the player's avatar which will be edited.
string [] EditProfileGUI.keys
Keys for labeling colors.
Dictionary<string, int> EditProfileGUI.selected
The ids of the currently selected colors for skin, top, and bottom.
Dictionary<string, TextureRect> EditProfileGUI.colorSelectors
Icons for labeling the currently selected colors.
/
readonly int EditProfileGUI.DEFAULT_COLOR
The id of the avatar default colors.
Referenced by _Ready.
delegate void EditProfileGUI.ProfileChanged()
Emitted if the user profile's data was modified.
override void EditProfileGUI._Ready()
References PlayerSession.ActiveSession, Profile.Avatar, DEFAULT_COLOR, Avatar.GetColor, Palette.Instance, Avatar.Male, Profile.Name, OnCancelPressed, OnColorPressed, OnGenderItemSelected, OnSavePressed, PlayerSession.Profile, Palette.TextureFromColor, UpdateAvatar, Main.WINDOW_SIZE.
override void EditProfileGUI._Process(float delta)
References PlayerSession.ActiveSession, lockSprite, Profile.OwnedItems, PlayerSession.Profile, UnsavedChanges, UpdateAvatar.
bool EditProfileGUI.UnsavedChanges()
Checks if the player has edited their avatar and the changes haven't been saved.
True if the changes are unsaved, false otherwise.
References PlayerSession.ActiveSession, Profile.Avatar, Avatar.Male, Profile.Name, PlayerSession.Profile.
Referenced by _Process.
void EditProfileGUI.UpdateAvatar()
Updates the data of the avatar being edited depending on user input. Displays the new avatar.
References Avatar.Male, Avatar.SetColor, Avatar.ToTexture.
Referenced by _Process, _Ready, OnColorPressed, OnGenderItemSelected.
void EditProfileGUI.OnColorPressed()
References UpdateAvatar.
Referenced by _Ready.
void EditProfileGUI.OnGenderItemSelected(int index)
References Avatar.Male, UpdateAvatar.
Referenced by _Ready.
void EditProfileGUI.OnCancelPressed()
Referenced by _Ready.
void EditProfileGUI.OnSavePressed()
References PlayerSession.ActiveSession, Profile.Avatar, Avatar.Male, Profile.Name, Profile.NameIsAvailable, PlayerSession.Profile, PlayerSession.Save.
Referenced by _Ready.