SecondaryAction
bool SecondaryAction.Blocked
Checks if the current action is blocked/disabled. If true, the action will not be performed on input events.
Referenced by SpawnPlatforms._ActionOnAir, _ActionOnGround, _ActionReleased, SwitchGravity.invertGravity, TeleportAndSwitchGravity.invertGravity.
override void SecondaryAction._Init()
Setups the state and initializes it.
References OnSecondaryActionTimerTimeout, Player.secondaryActionTimer.
override void SecondaryAction._StatePhysicsProcess(float delta)
The physics process that will be called each frame for the state.
delta Time since the last frame.
References _ActionOnAir, _ActionOnGround, _ActionReleased, Player.PersistentState.
Referenced by Player._PhysicsProcess.
virtual void SecondaryAction._ActionOnGround()
The action that will be executed if the player inputs the action's keys and the player's persistent state is on ground.
References Blocked, Player.secondaryActionTimer.
Referenced by _StatePhysicsProcess.
abstract void SecondaryAction._ActionOnAir()
The action that will be executed if the player inputs the action's keys and the player's persistent state is on air.
Referenced by _StatePhysicsProcess.
virtual void SecondaryAction._ActionReleased()
The action that will be executed once the player stops pressing the action's input keyboard/mouse buttons.
References Blocked.
Referenced by _StatePhysicsProcess.
virtual void SecondaryAction.OnSecondaryActionTimerTimeout()
References Player.animation, MainAction.Blocked, Player.MainAction, Player.secondaryActionTimer.
Referenced by _Init.
static string SecondaryAction.GetTypeAsString(PlayerSecondaryAction action)
Gets the given action's type as a string. This is because the player animations corresponding to each action has these names.
action The enum value of the action. A string depending on the action type.
Referenced by SecondaryActionPickup._Ready.
static string SecondaryAction.GetTypeAsStringEsp(PlayerSecondaryAction action)
Gets the given action's type as a string in spanish. This is for displaying on the GUI.
action The enum value of the action A string in spanish depending on the action type.
Referenced by GameHUD.SetActions.